version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/get-ethereum-assignment:latest
    container_name: app-devnet
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - devnet
networks:
  devnet:
    driver: bridge
