services:
  app:
    image: krishum77/get-etherium-assignment:latest
    platform: linux/amd64
    container_name: app-devnet
    ports:
      - "8545:8545"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - devnet
networks:
  devnet:
    driver: bridge
