name: Deployment GETH

on:
  pull_request:
    branches: [ "master" ]
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    # services:
    #   geth:
    #     image: ethereum/client-go:stable
    #     ports:
    #       - 8545:8545
    #     env:
    #       GETH_ARGS: "--dev --http --http.api eth,net,web3,personal --mine --miner.threads=1"

    # defaults:
    #   run:
    #     working-directory: hardhat

    steps:
      - name: Run GETH Client
        run: |
          docker pull --platform linux/amd64 krishum77/get-etherium-assignment
          docker run -d --platform linux/amd64 \
            --name devnet \
            -p 8545:8545 \
            krishum77/get-etherium-assignment
          docker ps
          docker logs devnet
          curl http://localhost:8545

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: hardhat/package-lock.json

      - name: Install deps (hardhat)
        working-directory: hardhat
        run: npm ci

      - name: Wait for Geth
        run: |
          docker ps
          echo "Waiting for Geth to start..."
          until curl -s http://localhost:8545 >/dev/null; do sleep 1; done
          echo "Geth is live"

      - name: Compile contracts
        working-directory: hardhat
        run: npx hardhat compile

      - name: Run tests
        working-directory: hardhat
        run: npx hardhat test --network geth

      - name: Deploy contract
        working-directory: hardhat
        run: npx hardhat run scripts/deploy.ts --network geth
