name: CI Deploy
 
on:
   pull_request:
     branches: [ "master" ]
     types: [closed]
 
jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Forked Repository Image in Devnet
        run: |
          docker pull krishum77/get-etherium-assignment:latest
          docker run -d -p 8545:8545 \
           -v ${{ github.workspace }}/chaindata:/root/.ethereum/devchain \
           --name devnet krishum77/get-etherium-assignment:latest \
           --datadir /root/.ethereum/devchain \
           --dev \
           --http \
           --http.addr 0.0.0.0 \
           --http.api web3,eth,debug,net \
           --http.vhosts=* \
           --http.corsdomain=* \
           --nodiscover

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: hardhat/package-lock.json

      - name: Install hardhat dependencies
        working-directory: hardhat
        run: npm ci

      - name: Wait for Geth
        run: |
          echo "Waiting for Geth to start..."
          timeout=180
          counter=0
          until curl -s http://localhost:8545 >/dev/null; do
            if [ $counter -ge $timeout ]; then
              echo "Timed out waiting for Geth to start after ${timeout} seconds"
              exit 1
            fi
            sleep 1
            counter=$((counter + 1))
            if [ $((counter % 10)) -eq 0 ]; then
              echo "Still waiting... ($counter seconds elapsed)"
            fi
          done
          echo "Geth is live"

      - name: Compile contracts
        working-directory: hardhat
        run: npx hardhat compile

      - name: Deploy Lock Contract to Devnet with a Custom Script
        working-directory: hardhat
        run: npx hardhat run scripts/deploy.ts --network devnet
         
      - name: Stop Geth Container and Copy Chain Data
        run: |
          sudo docker cp devnet:/root/.ethereum/devchain ./devchain
          mkdir -p gethdata
          sudo cp -r ./devchain/* gethdata/
          sudo chmod -R a+rX gethdata
          docker stop devnet
          
      - name: Create new Docker image with the Deployed Contract
        run: |
          cp Dockerfile.predeployedContracts Dockerfile
          docker build -t krishum77/geth-with-contracts:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run the New Image with Predeployed Contract
        run: |
          docker run -d -p 8545:8545 --name predeployed krishum77/geth-with-contracts:latest \
           --datadir /root/.ethereum/devchain \
           --dev \
           --http \
           --http.addr 0.0.0.0 \
           --http.api web3,eth,debug,net \
           --http.vhosts=* \
           --http.corsdomain=* \
           --nodiscover

      - name: Wait for Geth Redeployment
        run: |
          echo "Waiting for Geth to start..."
          timeout=180
          counter=0
          until curl -s http://localhost:8545 >/dev/null; do
            if [ $counter -ge $timeout ]; then
              echo "Timed out waiting for Geth to start after ${timeout} seconds"
              exit 1
            fi
            sleep 1
            counter=$((counter + 1))
            if [ $((counter % 10)) -eq 0 ]; then
              echo "Still waiting... ($counter seconds elapsed)"
            fi
          done
          echo "Geth is live"

      - name: Run Hardhat Tests before Pushing the Image to Registry
        working-directory: hardhat 
        run: npx hardhat test --network devnet

      - name: Push Docker image
        run: |
          docker push krishum77/geth-with-contracts:latest
