name: CI Deploy
 
on:
   pull_request:
     branches: [ "master" ]
     types: [closed]
 
jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Forked Repository Image
        run: |
          docker pull krishum77/get-etherium-assignment:latest
          docker run -d -p 8545:8545 \
           -v ${{ github.workspace }}/chaindata:/root/.ethereum/devchain \
           --name devnet krishum77/get-etherium-assignment:latest \
           --datadir /root/.ethereum/devchain \
           --dev \
           --http \
           --http.addr 0.0.0.0 \
           --http.api web3,eth,debug,net \
           --http.vhosts=* \
           --http.corsdomain=* \
           --nodiscover

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: hardhat/package-lock.json

      - name: Install hardhat dependencies
        working-directory: hardhat
        run: npm ci

      - name: Wait for Geth
        run: |
          echo "Waiting for Geth to start..."
          timeout=180
          counter=0
          until curl -s http://localhost:8545 >/dev/null; do
            if [ $counter -ge $timeout ]; then
              echo "Timed out waiting for Geth to start after ${timeout} seconds"
              exit 1
            fi
            sleep 1
            counter=$((counter + 1))
            if [ $((counter % 10)) -eq 0 ]; then
              echo "Still waiting... ($counter seconds elapsed)"
            fi
          done
          echo "Geth is live"

      - name: Show Geth logs
        run: docker logs devnet

      - name: Compile contracts
        working-directory: hardhat
        run: npx hardhat compile

      - name: Deploy Lock contract to devnet
        working-directory: hardhat
        # run: npx hardhat ignition deploy ./ignition/modules/Lock.ts --network devnet
        # env:
        #  HARDHAT_IGNITION_CONFIRM_DEPLOYMENT: false
         # PRIVATE_KEY: 4f3edf983ac636a65a842ce7c78d9aa706d3b113b37c936e9c37fda7f1f7c8c2
        run: npx hardhat run scripts/deploy.ts --network devnet

      - name: Show Geth logs
        run: | 
         docker logs devnet
         
         
      - name: Stop Geth Container and copy chain data
        run: |
          echo '---'
          docker exec devnet ls -a /root/.ethereum/devchain/geth/chaindata
          echo '---'
          docker stop devnet
          sudo docker cp devnet:/root/.ethereum/devchain ./chaindata
          ls -R ./chaindata
          du -sh ./chaindata
          
      - name: Create new Docker image with deployed contracts
        run: |
          cp Dockerfile.predeployedContracts Dockerfile
          docker build -t krishum77/geth-with-contracts:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push krishum77/geth-with-contracts:latest

      - name: Run the new image
        run: |
          docker run -d -p 8545:8545 --name predeployed krishum77/geth-with-contracts:latest \
           --dev \
           --http \
           --http.addr 0.0.0.0 \
           --http.api web3,eth,debug,net \
           --http.vhosts=* \
           --http.corsdomain=* \
           --nodiscover

      - name: Docker logs
        run: | 
         docker logs predeployed

      - name: Wait for Geth redeployed
        run: |
          echo "Waiting for Geth to start..."
          timeout=180
          counter=0
          until curl -s http://localhost:8545 >/dev/null; do
            if [ $counter -ge $timeout ]; then
              echo "Timed out waiting for Geth to start after ${timeout} seconds"
              exit 1
            fi
            sleep 1
            counter=$((counter + 1))
            if [ $((counter % 10)) -eq 0 ]; then
              echo "Still waiting... ($counter seconds elapsed)"
            fi
          done
          echo "Geth is live"

      # - name: Deploy Lock contract to devnet
        # working-directory: hardhat
        # run: npx hardhat ignition deploy ./ignition/modules/Lock.ts --network devnet
        # env:
        #  HARDHAT_IGNITION_CONFIRM_DEPLOYMENT: false
         # PRIVATE_KEY: 4f3edf983ac636a65a842ce7c78d9aa706d3b113b37c936e9c37fda7f1f7c8c2
        # run: npx hardhat run scripts/deploy.ts --network devnet

      - name: Docker logs
        run: | 
         docker exec predeployed ls -l /root/.ethereum
         docker logs predeployed

      # - name: Run tests
      #   working-directory: hardhat 
      #   run: npx hardhat test --network devnet
