name: CI Deploy
 
on:
   pull_request:
     branches: [ "master" ]
     types: [closed]
 
jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      # - name: Create geth data directory
      #   run: mkdir -p ./gethdata

      # - name: Initialize Geth with custom genesis
      #   run: |
      #     docker run --rm --platform linux/amd64 \
      #       -v ${{ github.workspace }}/gethdata:/root/.ethereum \
      #       -v ${{ github.workspace }}/hardhat/genesis.json:/genesis.json \
      #       krishum77/get-etherium-assignment init /genesis.json
      # - name: Start Geth node
      #   run: |
      #     docker run -d --platform linux/amd64 --name devnet \
      #       -v ${{ github.workspace }}/gethdata:/root/.ethereum \
      #       -p 8545:8545 \
      #       krishum77/get-etherium-assignment \
      #       --dev \
      #       --http --http.addr 0.0.0.0 \
      #       --http.api eth,web3,net,miner \
      #       --http.corsdomain="*" \
      #       --nodiscover --mine 
      - name: Run Forked Repository Image
        run: |
          docker pull --platform linux/amd64 krishum77/get-etherium-assignment
          docker run -d -p 8545:8545 -v ${{ github.workspace }}/chaindata:/root/.ethereum/devchain \ 
          --platform linux/amd64 --name devnet krishum77/get-etherium-assignment \
            --dev \
            --http \
            --http.addr 0.0.0.0 \
            --http.api web3,eth,debug,net \
            --http.vhosts=* \
            --http.corsdomain=* \
            --nodiscover

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: hardhat/package-lock.json

      - name: Install hardhat dependencies
        working-directory: hardhat
        run: npm ci

      - name: Show Geth logs
        run: docker logs devnet

      - name: Wait for Geth
        run: |
          echo "Waiting for Geth to start..."
          timeout=180
          counter=0
          until curl -s http://localhost:8545 >/dev/null; do
            if [ $counter -ge $timeout ]; then
              echo "Timed out waiting for Geth to start after ${timeout} seconds"
              exit 1
            fi
            sleep 1
            counter=$((counter + 1))
            if [ $((counter % 10)) -eq 0 ]; then
              echo "Still waiting... ($counter seconds elapsed)"
            fi
          done
          echo "Geth is live"

      - name: Check account balance
        run: |
          echo "Querying balance..."
          RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" \
           --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x5409ed021d9299bf6814279a6a1411a7e866a631", "latest"],"id":1}' \
           http://localhost:8545 | jq .)
          echo "Balance response: $RESPONSE"

      - name: Show Geth logs
        run: docker logs devnet

      - name: Compile contracts
        working-directory: hardhat
        run: npx hardhat compile

      - name: Deploy Lock contract to devnet
        working-directory: hardhat
        # run: npx hardhat ignition deploy ./ignition/modules/Lock.ts --network devnet
        # env:
        #  HARDHAT_IGNITION_CONFIRM_DEPLOYMENT: false
         # PRIVATE_KEY: 4f3edf983ac636a65a842ce7c78d9aa706d3b113b37c936e9c37fda7f1f7c8c2
        run: npx hardhat run scripts/deploy.ts --network devnet

      # - name: Run tests
      #   working-directory: hardhat
      #   run: npx hardhat test --network devnet

      # - name: Show Geth logs
      #   run: docker logs devnet

      - name: Copy deployments file
        run: |
          docker cp devnet:/root/.ethereum/devchain ./chaindata
          
      - name: Create new Docker image with deployed contracts
        run: |
          # Create a Dockerfile for the new image
          cat > Dockerfile.deployed << EOF
          FROM krishum77/get-etherium-assignment
          
          # Copy the deployment info
          COPY /tmp/geth-data/deployments.json /deployments.json
          
          # Set default command
          CMD ["--dev", "--http", "--http.addr", "0.0.0.0", "--http.api", "web3,eth,debug,net", "--http.vhosts=*", "--http.corsdomain=*", "--nodiscover"]
          EOF
          
          # Build the new image
          docker build -f Dockerfile.deployed -t krishum77/get-etherium-assignment:with-contracts .
          
      - name: Stop existing devnet
        run: docker stop devnet || true
