name: CI Deploy
 
on:
   pull_request:
     branches: [ "master" ]
     types: [closed]
 
jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Run Forked Repository Image
        run: |
          docker pull --platform linux/amd64 krishum77/get-etherium-assignment
          docker run -d -p 8545:8545 --platform linux/amd64 --name localhost krishum77/get-etherium-assignment \
            --dev \
            --http \
            --http.addr 0.0.0.0 \
            --http.api web3,eth,debug,net,personal \
            --http.vhosts=* \
            --http.corsdomain=* \
            --nodiscover

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: hardhat/package-lock.json

      - name: Install hardhat dependencies
        working-directory: hardhat
        run: npm ci

      - name: Wait for Geth
        run: |
          echo "Waiting for Geth to start..."
          timeout=180
          counter=0
          until curl -s http://localhost:8545 >/dev/null; do
            if [ $counter -ge $timeout ]; then
              echo "Timed out waiting for Geth to start after ${timeout} seconds"
              exit 1
            fi
            sleep 1
            counter=$((counter + 1))
            if [ $((counter % 10)) -eq 0 ]; then
              echo "Still waiting... ($counter seconds elapsed)"
            fi
          done
          echo "Geth is live"

      - name: Check account balance
        run: |
          echo "Querying balance..."
          RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" \
           --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xe346cd9559B3079F1c27EEbDc3D763DB860eA725", "latest"],"id":1}' \
           http://localhost:8545 | jq .)
          echo "Balance response: $RESPONSE"

      - name: Show Geth logs
        run: docker logs localhost

       
      - name: Compile contracts
        working-directory: hardhat
        run: npx hardhat compile

      - name: Deploy Lock contract to devnet
        working-directory: hardhat
        run: npx hardhat ignition deploy ./ignition/modules/Lock.ts --network localhost
        env:
         HARDHAT_IGNITION_CONFIRM_DEPLOYMENT: false
         PRIVATE_KEY: 4f3edf983ac636a65a842ce7c78d9aa706d3b113b37c936e9c37fda7f1f7c8c2
        # npx hardhat run scripts/deploy.ts --network devnet
